name: RELEASE

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Set up linter
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Build
      run: make build

  release:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Release
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.Release-CI }}
        RELEASE_NAME_PREFIX: "v"

